import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased dark:bg-black dark:text-white`}
      >
        <div className="dark bg-black text-white min-h-screen flex flex-col">
          <Header />
          <main className="relative px-7 flex-1 flex flex-col pt-24 pb-32 overflow-y-auto overflow-x-hidden">
            {/* Grid background overlay */}
            <div
              aria-hidden
              className="pointer-events-none absolute inset-0 z-0 bg-[radial-gradient(circle,rgba(255,255,255,0.04)_1px,transparent_1px)] [background-size:32px_32px]"
            />
            <div className="relative z-10">{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
